### ISSUE TITLE
Out-of-source build doesn't work out of box

### ISSUE THREAD

**Issue by eustas** [nemequ/configure-cmake#10]
[at least for brotli] current directory is not used as a destination of generated build files.
Scenario like this won't work as expected:
`mkdir out && cd out && ../configure`
A hack is required to fix behaviour:
`mkdir out && cd out && ../configure `**`--pass-thru -B.`**

**Comment by nemequ** [comment]
Can you be more specific?  That's how I always build stuff with this script and it always works.  I also just tried dropping a copy of this script in my brotli tree, and it works as expected.

**Comment by eustas** [comment]
Oh, the things break only if someone occasionally runs `./configure` in root project folder.
After this CMake sticks to root folder, unless `-B.` is specified (because of CMakeCache.txt file).

**Comment by nemequ** [comment]
Ah, [that makes sense](https://cmake.org/Wiki/CMake_FAQ#I_run_an_out-of-source_build_but_CMake_generates_in-source_anyway._Why.3F).

I don't see the -B flag documented anywhere, where are you getting that?  It's not in [cmake(1)](https://cmake.org/cmake/help/v3.7/manual/cmake.1.html)…  If that's something we could add to the cmake command without causing problems I'd be willing to do so, but this seems like more of a CMake problem, and they don't seem interested in fixing it.
