### ISSUE TITLE
"--pass-thru -GNinja .." results in error "shift: can't shift that many"

### ISSUE THREAD

**Issue by sqz** [nemequ/configure-cmake#11]
This is a brilliant script and while I have got it working in general, it uses the default of "Unix Makefiles" on UNIX-like platforms, which is understandable for traditional compatibility reasons.

I attempted to use the very common but different generator, Ninja, by using the "--pass-thru" option like so (sitting in the 'build' sub-directory of a project with CMakeLists.txt and configure script parent directory):

`../configure --pass-thru -GNinja`

and it failed with the error 

> ../configure: 303: shift: can't shift that many

Am I using the wrong syntax?

**Comment by nemequ** [comment]
I've seen that in another project; bash is fine with it, but not dash.  Are you on a distro where /bin/sh is dash (like Ubuntu)?

Can you try

```diff
diff --git a/configure b/configure
index a383d31..a8a75d5 100755
--- a/configure
+++ b/configure
@@ -270,10 +270,9 @@ while [ $# != 0 ]; do
             BUILD_TYPE="Release";;
 
         "--pass-thru")
-            shift;
-            while [ $# != 0 ]; do
-                CMAKE_ARGS="$CMAKE_ARGS $(quote "${1}")";
+            while [ $# != 1 ]; do
                 shift;
+                CMAKE_ARGS="$CMAKE_ARGS $(quote "${1}")";
             done;;
 
         "--enable-"*)
```

?

**Comment by sqz** [comment]
Yes, I am on Ubuntu 16.04 LTS.

That works, thank you! And for your insanely fast response :)

**Comment by nemequ** [comment]
Excellent, fixed in master, thanks!
