### ISSUE TITLE
Feature Request: --enable-<something> and --with-<something> support

### ISSUE THREAD

**Issue by rilian-la-te** [nemequ/configure-cmake#2]
translate `--enable-<something>` to `-DENABLE_<SOMETHING>=ON` and `--disable-<something>` to `-DENABLE_<SOMETHING>=OFF` (notice uppercase here). I think this will be useful for many CMake projects.
For non-binary options it can be: `--with-<something>=a` to `-DSOMETHING=a`

What do you think about this?

**Comment by nemequ** [comment]
Done.  Let me know if you have any trouble with it.
