### ISSUE TITLE
Feature request: support gentoo econf

### ISSUE THREAD

**Issue by rilian-la-te** [nemequ/configure-cmake#4]
For now it crashed with unrecognized option

**Comment by nemequ** [comment]
Can you post the options econf tried to pass to configure?

**Comment by rilian-la-te** [comment]
Here is an example (not from CMake project):

```
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --libdir=/usr/lib64 --docdir=/usr/share/doc/file-roller-3.14.2 --disable-schemas-compile --disable-run-in-place --disable-static --disable-debug --enable-magic --enable-libarchive --disable-nautilus-actions --disable-packagekit ITSTOOL=/bin/true
```

Enables and disables may vary (except --disable-silent-rules and --disable-dependency-tracking)

**Comment by nemequ** [comment]
A lot of those options don't really have direct CMake equivalents:
- build / host — it might be possible to translate these to CMAKE_SYSTEM_NAME/PROCESSOR, but AFAIK it would be distro-specific, so not really feasible.
- disable-dependency-tracking — I don't know of anything in CMake which would enable this
- disable-silent-rules — CMake is quiet by default.  I guess we could silently ignore this, but there isn't a way to handle the inverse (enable-silent-rules)… AFAIK the only way to do this with CMake is to pass VERBOSE=1 to _make_, but cmake doesn't have anything to switch the default at the configure stage.
- disable-schemas-compile, enable-magic, enable-libarchive, disable-nautilus-actions, disable-packagekit are, AFAICT, project-specific, and you can add them if you want using a `.configure-custom.sh` file
- ITSTOOL — I believe autotools just add environment variables when you pass things like that, I don't think there is a generic equivalent in CMake.  The closest would be to do something like -DITSTOOL=/bin/true, but that will cause an error if the ITSTOOL variable isn't used.

I think that it would be better to just call cmake directly in situations like this.

**Comment by nemequ** [comment]
FWIW, if you can think of a way to pull any of those off feel free to reopen this.  I just don't think it's possible :(
