### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by eustas** [nemequ/configure-cmake#9]
* is `CMAKE_CMD` variable used?
* should the script check that `cmake` is installed/available and recommend users to install it if not?

**Comment by nemequ** [comment]
> is CMAKE_CMD variable used?

It isn't, but it should be.  And it should probably just be `cmake` not `cmake ${TOP_SRCDIR}`, an if it's set before the script is called we should use that value.  I'll change it this afternoon.

> should the script check that cmake is installed/available and recommend users to install it if not?

I don't think it's really necessary.  If CMake isn't installed, the user will get a `cmake: command not found` error, which seems pretty self-explanatory to me.  That said, I don't really have a problem adding it if you want.

**Comment by eustas** [comment]
Thanks.
